# Generated by Django 3.2 on 2021-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20210413_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_status',
            field=models.IntegerField(verbose_name='Статус'),
        ),
    ]
