# Generated by Django 3.2 on 2021-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Общий'),
        ),
    ]
