# Generated by Django 3.2 on 2021-06-12 12:12

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_messagefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefiles',
            name='name',
            field=models.CharField(default='<django.db.models.fields.files.FileField>', max_length=50, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='messagefiles',
            name='file',
            field=models.FileField(upload_to=messenger.models.MessageFiles.get_upload_path),
        ),
    ]
