# Generated by Django 3.2 on 2021-06-13 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20210612_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefiles',
            name='name',
            field=models.CharField(default='NoNameFile', max_length=50, verbose_name='Имя файла'),
        ),
        migrations.CreateModel(
            name='Chat_Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='messenger.chat')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
