# Generated by Django 3.2 on 2021-06-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_auto_20210613_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat_Moderator',
        ),
    ]
