# Generated by Django 3.2 on 2021-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_delete_chat_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_audio',
            field=models.BooleanField(default=False, verbose_name='Голосовое сообщение'),
        ),
    ]
